{
 "title": "Seuron Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   { "name": "chunkflow_run_id", "label": "Chunkflow Run:", "query": { "query": "label_values(chunkflow_run_id)" } },
   {
    "name": "segmentation_run_id",
    "label": "Segmentation Run:",
    "query": {
     "query": "label_values(segmentation_run_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Chunkflow Run: $chunkflow_run_id",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "chunkflow_run_id",
   "collapsed": true,
   "panels": [
    {
     "title": "Processing rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 19, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(seuron_agg_chunkflow_operator_duration_count{chunkflow_run_id=\"$chunkflow_run_id\", chunkflow_task_id!=\"patch_inference\"}[1m])",
       "legendFormat": "{{chunkflow_task_id}}"
      }
     ]
    },
    {
     "title": "Average patch inference time",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 19, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "seuron_agg_chunkflow_operator_duration_sum{chunkflow_task_id=\"patch_inference\", chunkflow_run_id=\"$chunkflow_run_id\"}/seuron_agg_chunkflow_operator_duration_count{chunkflow_task_id=\"patch_inference\", chunkflow_run_id=\"$chunkflow_run_id\"}",
       "legendFormat": "{{chunkflow_run_id}}"
      }
     ]
    },
    {
     "title": "Average processing time per chunk",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "seuron_agg_chunkflow_operator_duration_sum{chunkflow_task_id!=\"patch_inference\",chunkflow_run_id=\"$chunkflow_run_id\"}/seuron_agg_chunkflow_operator_duration_count{chunkflow_task_id!=\"patch_inference\", chunkflow_run_id=\"$chunkflow_run_id\"}",
       "legendFormat": "{{chunkflow_task_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Segmentation Run: $segmentation_run_id",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "repeat": "segmentation_run_id",
   "collapsed": true,
   "panels": [
    { "type": "text", "gridPos": { "h": 13, "w": 4, "x": 0, "y": 2 }, "options": { "content": "# Watershed:" } },
    {
     "title": "Processing rate",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 20, "x": 4, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(seuron_agg_segmentation_operator_duration_count{segmentation_component_id=\"ws\", segmentation_run_id=\"$segmentation_run_id\"}[1m])",
       "legendFormat": "layer {{segmentation_layer_id}}"
      }
     ]
    },
    {
     "title": "Number of chunks",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 20, "x": 4, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "seuron_agg_segmentation_operator_duration_count{segmentation_component_id=\"ws\", segmentation_run_id=\"$segmentation_run_id\"}",
       "legendFormat": "layer {{segmentation_layer_id}}"
      }
     ]
    },
    {
     "title": "Average chunk processing time",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 20, "x": 4, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "seuron_agg_segmentation_operator_duration_sum{segmentation_component_id=\"ws\", segmentation_run_id=\"$segmentation_run_id\"}/seuron_agg_segmentation_operator_duration_count{segmentation_component_id=\"ws\", segmentation_run_id=\"$segmentation_run_id\"}",
       "legendFormat": "layer {{segmentation_layer_id}}"
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 13, "w": 4, "x": 0, "y": 15 }, "options": { "content": "# Agglomeration:" } },
    {
     "title": "Processing rate",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 20, "x": 4, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(seuron_agg_segmentation_operator_duration_count{segmentation_component_id=\"agg\", segmentation_run_id=\"$segmentation_run_id\"}[1m])",
       "legendFormat": "layer {{segmentation_layer_id}}"
      }
     ]
    },
    {
     "title": "Number of chunks",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 20, "x": 4, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "seuron_agg_segmentation_operator_duration_count{segmentation_component_id=\"agg\", segmentation_run_id=\"$segmentation_run_id\"}",
       "legendFormat": "layer {{segmentation_layer_id}}"
      }
     ]
    },
    {
     "title": "Average chunk processing time in each layer",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 20, "x": 4, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "seuron_agg_segmentation_operator_duration_sum{segmentation_component_id=\"agg\", segmentation_run_id=\"$segmentation_run_id\"}/seuron_agg_segmentation_operator_duration_count{segmentation_component_id=\"agg\", segmentation_run_id=\"$segmentation_run_id\"}",
       "legendFormat": "layer {{segmentation_layer_id}}"
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 13, "w": 4, "x": 0, "y": 28 }, "options": { "content": "# Igneous:" } },
    {
     "title": "Processing rate",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 20, "x": 4, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(seuron_agg_segmentation_operator_duration_count{segmentation_component_id=\"igneous\", segmentation_run_id=\"$segmentation_run_id\"}[1m])",
       "legendFormat": "{{segmentation_layer_id}}"
      }
     ]
    },
    {
     "title": "Number of chunks",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 20, "x": 4, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "seuron_agg_segmentation_operator_duration_count{segmentation_component_id=\"igneous\", segmentation_run_id=\"$segmentation_run_id\"}",
       "legendFormat": "{{segmentation_layer_id}}"
      }
     ]
    },
    {
     "title": "Average chunk processing time in each layer",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 20, "x": 4, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "seuron_agg_segmentation_operator_duration_sum{segmentation_component_id=\"igneous\", segmentation_run_id=\"$segmentation_run_id\"}/seuron_agg_segmentation_operator_duration_count{segmentation_component_id=\"igneous\", segmentation_run_id=\"$segmentation_run_id\"}",
       "legendFormat": "{{segmentation_layer_id}}"
      }
     ]
    }
   ]
  }
 ]
}