{
 "title": "Seuron Cluster Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "stackdriver" },
   { "name": "DS_POSTGRESQL", "label": "Datasource", "query": "postgres" },
   {
    "name": "project",
    "label": "Project",
    "query": {}
   },
   {
    "name": "alignmentPeriod",
    "label": "Alignment Period",
    "query": {}
   },
   {
    "name": "deployment",
    "label": "Deployment",
    "query": "select host from connection where conn_id = 'InstanceGroups';"
   }
  ]
 },
 "panels": [
  {
   "title": "Manager - CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "manager node",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "editorMode": "visual",
      "filters": [
       "resource.type",
       "=",
       "gce_instance",
       "AND",
       "metric.label.instance_name",
       "=",
       "${deployment}-bootstrap"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "compute.googleapis.com/instance/cpu/utilization",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "$project",
      "query": "",
      "unit": "10^2.%",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "GCE VM Instance - CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{metadata.system_labels.instance_group}}",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "editorMode": "visual",
      "filters": [
       "resource.type",
       "=",
       "gce_instance",
       "AND",
       "metric.label.instance_name",
       "=",
       "${deployment}*"
      ],
      "groupBys": [
       "metadata.system_labels.instance_group"
      ],
      "metricKind": "GAUGE",
      "metricType": "compute.googleapis.com/instance/cpu/utilization",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "$project",
      "query": "",
      "unit": "10^2.%",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "GCE VM Instance - Uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{metadata.system_labels.instance_group}}",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "editorMode": "visual",
      "filters": [
       "resource.type",
       "=",
       "gce_instance",
       "AND",
       "metric.label.instance_name",
       "=",
       "${deployment}*"
      ],
      "groupBys": [
       "metadata.system_labels.instance_group"
      ],
      "metricKind": "DELTA",
      "metricType": "compute.googleapis.com/instance/uptime",
      "perSeriesAligner": "ALIGN_RATE",
      "preprocessor": "none",
      "projectName": "$project",
      "query": "",
      "unit": "s{uptime}",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Disk read operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{metadata.system_labels.instance_group}}",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "editorMode": "visual",
      "filters": [
       "resource.type",
       "=",
       "gce_instance",
       "AND",
       "metric.label.instance_name",
       "=",
       "${deployment}*"
      ],
      "groupBys": [
       "metadata.system_labels.instance_group"
      ],
      "metricKind": "DELTA",
      "metricType": "compute.googleapis.com/instance/disk/read_ops_count",
      "perSeriesAligner": "ALIGN_RATE",
      "preprocessor": "none",
      "projectName": "$project",
      "query": "",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Disk write operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{metadata.system_labels.instance_group}}",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "editorMode": "visual",
      "filters": [
       "resource.type",
       "=",
       "gce_instance",
       "AND",
       "metric.label.instance_name",
       "=",
       "${deployment}*"
      ],
      "groupBys": [
       "metadata.system_labels.instance_group"
      ],
      "metricKind": "DELTA",
      "metricType": "compute.googleapis.com/instance/disk/write_ops_count",
      "perSeriesAligner": "ALIGN_RATE",
      "preprocessor": "none",
      "projectName": "$project",
      "query": "",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Disk read bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{metadata.system_labels.instance_group}}",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "editorMode": "visual",
      "filters": [
       "resource.type",
       "=",
       "gce_instance",
       "AND",
       "metric.label.instance_name",
       "=",
       "${deployment}*"
      ],
      "groupBys": [
       "metadata.system_labels.instance_group"
      ],
      "metricKind": "DELTA",
      "metricType": "compute.googleapis.com/instance/disk/read_bytes_count",
      "perSeriesAligner": "ALIGN_RATE",
      "preprocessor": "none",
      "projectName": "$project",
      "query": "",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Disk write bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{metadata.system_labels.instance_group}}",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "editorMode": "visual",
      "filters": [
       "resource.type",
       "=",
       "gce_instance",
       "AND",
       "metric.label.instance_name",
       "=",
       "${deployment}*"
      ],
      "groupBys": [
       "metadata.system_labels.instance_group"
      ],
      "metricKind": "DELTA",
      "metricType": "compute.googleapis.com/instance/disk/write_bytes_count",
      "perSeriesAligner": "ALIGN_RATE",
      "preprocessor": "none",
      "projectName": "$project",
      "query": "",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "GCE VM Instance - Received packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{metadata.system_labels.instance_group}}",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "editorMode": "visual",
      "filters": [
       "resource.type",
       "=",
       "gce_instance",
       "AND",
       "metric.label.instance_name",
       "=",
       "${deployment}*"
      ],
      "groupBys": [
       "metadata.system_labels.instance_group"
      ],
      "metricKind": "DELTA",
      "metricType": "compute.googleapis.com/instance/network/received_packets_count",
      "perSeriesAligner": "ALIGN_RATE",
      "preprocessor": "none",
      "projectName": "$project",
      "query": "",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "GCE VM Instance - Sent packets count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{metadata.system_labels.instance_group}}",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "editorMode": "visual",
      "filters": [
       "resource.type",
       "=",
       "gce_instance",
       "AND",
       "metric.label.instance_name",
       "=",
       "${deployment}*"
      ],
      "groupBys": [
       "metadata.system_labels.instance_group"
      ],
      "metricKind": "DELTA",
      "metricType": "compute.googleapis.com/instance/network/sent_packets_count",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "rate",
      "projectName": "$project",
      "query": "",
      "unit": "{packet}",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "GCE VM Instance - Received bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{metadata.system_labels.instance_group}}",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "editorMode": "visual",
      "filters": [
       "resource.type",
       "=",
       "gce_instance",
       "AND",
       "metric.label.instance_name",
       "=",
       "${deployment}*"
      ],
      "groupBys": [
       "metadata.system_labels.instance_group"
      ],
      "metricKind": "DELTA",
      "metricType": "compute.googleapis.com/instance/network/received_bytes_count",
      "perSeriesAligner": "ALIGN_RATE",
      "preprocessor": "none",
      "projectName": "$project",
      "query": "",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "GCE VM Instance - Sent bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{metadata.system_labels.instance_group}}",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "editorMode": "visual",
      "filters": [
       "resource.type",
       "=",
       "gce_instance",
       "AND",
       "metric.label.instance_name",
       "=",
       "${deployment}*"
      ],
      "groupBys": [
       "metadata.system_labels.instance_group"
      ],
      "metricKind": "DELTA",
      "metricType": "compute.googleapis.com/instance/network/sent_bytes_count",
      "perSeriesAligner": "ALIGN_RATE",
      "preprocessor": "none",
      "projectName": "$project",
      "query": "",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  }
 ]
}